### ISSUE TITLE
Multi World

### ISSUE THREAD

**Issue by MattPuffin** [nkomarn/harbor#1]
Not an issue at all, just didnt know where else to contact you!
I noticed on the changelog that in 1.4 you've added multiworld support, but i cant work out how to set it up!
Thanks,
Matt

**Comment by MattPuffin** [comment]
Ok i've clearly jinxed it by saying it wasnt an issue! :')
Im running spigot 1.13.1
whenever a player sleeps i get this error in the console
https://pastebin.com/0WSznaUz

**Comment by nkomarn** [comment]
@MattPuffin The multi-world support is actually automatic. It basically makes it so that ever single world on your server has a separate sleeping player count. If you have a suggestion for the feature, I'd love to hear it :)
