### ISSUE TITLE
Float value

### ISSUE THREAD

**Issue by TheAshenWolf** [nkomarn/harbor#10]
Hey there, as we usually go to sleep on the server, it often says "0 players remaining" and it is still night time. It looks like (from my point of view, but I am no expert) there is a value counted as a Float inside your sendActionbar function, inside Main. I am not sure if this is the place where to look at or if it is somewhere else, but it would be much appreciated to be set as an integer, so we do not have to look for like "0.4" of a player. Thanks very much, keep up the great work!

**Comment by nkomarn** [comment]
> Hey there, as we usually go to sleep on the server, it often says "0 players remaining" and it is still night time. It looks like (from my point of view, but I am no expert) there is a value counted as a Float inside your sendActionbar function, inside Main. I am not sure if this is the place where to look at or if it is somewhere else, but it would be much appreciated to be set as an integer, so we do not have to look for like "0.4" of a player. Thanks very much, keep up the great work!

Some of the math isn't the best, I would need to just do some rounding to make it work properly. I'll work on fixing that up as soon as I can! Thanks for bringing this to my attention :)
