### ISSUE TITLE
Admins with bypass permission can't sleep

### ISSUE THREAD

**Issue by JadenDevon** [nkomarn/harbor#11]
My admins keep getting attacked by phantoms because they are unable to sleep the night away due to the bypass permission. Can you make it so that they count towards the needed sleep number when they sleep, but don't count toward the total number of players?

**Comment by nkomarn** [comment]
> 
> 
> My admins keep getting attacked by phantoms because they are unable to sleep the night away due to the bypass permission. Can you make it so that they count towards the needed sleep number when they sleep, but don't count toward the total number of players?

I'll make sure I add this in for the next update!

**Comment by JadenDevon** [comment]
Awesome! Thank you!
