### ISSUE TITLE
Doesnt work when people disconnecting

### ISSUE THREAD

**Issue by hornta** [nkomarn/harbor#14]
Using all the default settings.

3 people are online.
1 person is sleeping - One more is needed for it to skip night.
1 person is disconnecting - Now it should skip the night since half the players are sleeping, but I have to re-enter the bed for it to take effect.
Is it a known issue?

**Comment by nkomarn** [comment]
> Using all the default settings.
> 
> 3 people are online.
> 1 person is sleeping - One more is needed for it to skip night.
> 1 person is disconnecting - Now it should skip the night since half the players are sleeping, but I have to re-enter the bed for it to take effect.
> Is it a known issue?

This is an issue with how the plugin handles sleep checks. Basically, the plugin only checks if there are enough players to skip when someone enters a bed. I'm going to go ahead and fix that for Harbor 1.5 (currently working on it).

**Comment by nkomarn** [comment]
Fixed for next release!
