### ISSUE TITLE
Sleep attempt during day increments sleeping count

### ISSUE THREAD

**Issue by cjucoder** [nkomarn/harbor#2]
Hi.  Using Harbor v1.4 on a Spigot 1.13.2 server, made no changes to the default config.yml,

 I was the only player online and made several attempts to sleep during the day.  The following messages were shown in the client and in the log....

[21:27:13] [Server thread/INFO]: cjucoder is now sleeping (1/1. 0 more needed to skip).
[21:27:16] [Server thread/INFO]: cjucoder is now sleeping (2/1. 0 more needed to skip).
[21:27:18] [Server thread/INFO]: cjucoder is now sleeping (3/1. 0 more needed to skip).
[21:27:20] [Server thread/INFO]: cjucoder is now sleeping (4/1. 0 more needed to skip).
[21:27:22] [Server thread/INFO]: cjucoder is now sleeping (5/1. 0 more needed to skip).
[21:27:23] [Server thread/INFO]: cjucoder is now sleeping (6/1. 0 more needed to skip).
[21:27:28] [Server thread/INFO]: cjucoder is now sleeping (7/1. 0 more needed to skip).
[21:30:13] [Server thread/INFO]: cjucoder is now sleeping (8/1. 0 more needed to skip).

---snip--- set the server to night so sleep attempts would be successful

[21:38:25] [Server thread/INFO]: Set the time to 13000
[21:38:28] [Server thread/INFO]: cjucoder is now sleeping (9/1. 0 more needed to skip).
[21:38:28] [Server thread/INFO]: cjucoder has made the advancement [Sweet Dreams]
[21:38:49] [Server thread/INFO]: cjucoder is now sleeping (9/1. 0 more needed to skip).
[21:39:41] [Server thread/INFO]: cjucoder is now sleeping (9/1. 0 more needed to skip).

**Comment by Synt3x** [comment]
I can confirm this problem. It's happens when you trying to sleep during the day. The X in (X/Y) is increasing everytime you rightclick bed.

**Comment by Synt3x** [comment]
@nkomarn, how do you feel about not supporting versions pre 1.13.2?
Because [this](https://github.com/nkomarn/Harbor/blob/master/Harbor/src/techtoolbox/Harbor/Listeners/BedEnterEvent.java) class is using _PlayerBedEnterEvent_ and it's deprecated.

This function most be wrapped with something checking if player have the ability to sleep. https://github.com/nkomarn/Harbor/blob/213de16f5c231318ec0143b67adf4c7e8f294b35/Harbor/src/techtoolbox/Harbor/Listeners/BedEnterEvent.java#L22

I can try make a new pull request, if you don't have any problem with not supporting versions pre 1.13.2.
I manage to solve the problem on my local fork for minecraft 1.13.2.

**Comment by timmyRS** [comment]
In my plugin, I've solved this issue by waiting for five ticks and then checking if the player is still sleeping:
https://github.com/timmyrs/SurvivalUtils/blob/1.4.2/src/de/timmyrs/SurvivalUtils.java#L479-L500

**Comment by Synt3x** [comment]
@timmyrs that's a good idea. You can also solve it by checking the result of the event.
```
if (event.getbedEnterResult() == BedEnterResult.OK) {
 // sleep code
}
```

I didn't find this in my first attempt to fix the problem, I used the time to calculate if the player could sleep. This code above doesn't work in older versions of Spigot.

[PlayerBedEnterEvent doc](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerBedEnterEvent.html)

**Comment by timmyRS** [comment]
My code worked down to 1.7.9, so it's probably a better solution.

**Comment by nkomarn** [comment]
> 
> 
> @nkomarn, how do you feel about not supporting versions pre 1.13.2?
> Because [this](https://github.com/nkomarn/Harbor/blob/master/Harbor/src/techtoolbox/Harbor/Listeners/BedEnterEvent.java) class is using _PlayerBedEnterEvent_ and it's deprecated.
> 
> This function most be wrapped with something checking if player have the ability to sleep.
> 
> [Harbor/Harbor/src/techtoolbox/Harbor/Listeners/BedEnterEvent.java](https://github.com/nkomarn/Harbor/blob/213de16f5c231318ec0143b67adf4c7e8f294b35/Harbor/src/techtoolbox/Harbor/Listeners/BedEnterEvent.java#L22)
> 
> Line 22 in [213de16](/nkomarn/Harbor/commit/213de16f5c231318ec0143b67adf4c7e8f294b35)
>  if (!event.getPlayer().hasPermission("harbor.bypass")) { 
> 
> I can try make a new pull request, if you don't have any problem with not supporting versions pre 1.13.2.
> I manage to solve the problem on my local fork for minecraft 1.13.2.

Could you show me the code for bed entry in your local fork? I am trying to fix the issue but I am a bit confused :/

**Comment by nkomarn** [comment]
I have fixed the issue for now, thanks for all the help!

**Comment by timmyRS** [comment]
You know the point of Github is to have the actual code on here?
