### ISSUE TITLE
Night skip triggers whenever a player leaves.

### ISSUE THREAD

**Issue by Weasel-Beans** [nkomarn/harbor#22]
On my server (IP: 'beanscraft.ca'), the time is set to morning whenever someone disconnects. I am using the latest version of Harbor on Paper 1.14.3.

https://timings.aikar.co/?id=61e95bb37d3b4e8eb61315875dae9168

**Comment by nkomarn** [comment]
Give the latest beta from https://harbor.nkomarn.xyz a shot and let me know if the issue is resolved (I am 90% sure I fixed it in that release).

**Comment by Weasel-Beans** [comment]
That seems to work, thanks.

**Comment by NoManaSendHelp** [comment]
Still happening for me on the latest harbor build 1.5b6 and i'm on paper 131 (1.14.3)

**Comment by nkomarn** [comment]
> Still happening for me on the latest harbor build 1.5b6 and i'm on paper 131 (1.14.3)

1.5b6 is not the latest version. The latest build available is 1.5.1b1. You downloaded a beta for 1.5, not 1.5.1.

**Comment by NoManaSendHelp** [comment]
Oh sorry, will get it installed, my b
