### ISSUE TITLE
Updater Issue

### ISSUE THREAD

**Issue by vertex101** [nkomarn/harbor#23]
think there is an issue with the updater

`
15.07 14:35:00 [Server] Server thread/INFO [Harbor] Enabling Harbor v1.5.1
15.07 14:35:05 [Server] Server thread/ERROR Error occurred while enabling Harbor v1.5.1 (Is it up to date?)
15.07 14:35:05 [Server] INFO java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
15.07 14:35:05 [Server] INFO at mykyta.Harbor.Updater.check(Updater.java:37) ~[?:?]
15.07 14:35:05 [Server] INFO at mykyta.Harbor.Harbor.onEnable(Harbor.java:52) ~[?:?]
15.07 14:35:05 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:439) [spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764) [spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
15.07 14:35:05 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
15.07 14:35:05 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
15.07 14:35:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-604c8bf]
15.07 14:35:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
15.07 14:35:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
15.07 14:35:05 [Server] INFO ... 11 more
`

**Comment by nkomarn** [comment]
Fixed for 1.5.1.
