### ISSUE TITLE
Error on Player Join Event

### ISSUE THREAD

**Issue by stw222** [nkomarn/harbor#25]
Paper 131 for 1.14.3
console error:
[https://pastebin.com/Ahk4rEzC](https://pastebin.com/Ahk4rEzC)

config:
[https://pastebin.com/jwb8juhi](https://pastebin.com/jwb8juhi)

plugins: essentialsx core, chat, geoip, protect, and spawn ver 2.17.0.3, harbor 1.5.1b1, protocol lib, and vault

**Comment by ZandercraftGames** [comment]
@nkomarn Why did you close this issue? It is valid and still exists in harbor 1.5.2.

**Comment by nkomarn** [comment]
> @nkomarn Why did you close this issue? It is valid and still exists in harbor 1.5.2.

It's closed because I have fixed it for 1.5.3!

**Comment by ZandercraftGames** [comment]
Okay. Thanks. When will 1.5.3 be released?
