### ISSUE TITLE
Playerbedenterevent / leave event

### ISSUE THREAD

**Issue by stw222** [nkomarn/harbor#26]
i keep getting this error when entering or leaving a bed on harbor v1.5.2(even though it says 1.5.1 i have the 1.5.2 jar. i am using Paper 137 for 1.14.4 and was having the same error on 1.14.3
sometimes the night will skip like its supposed to, other times it wont

[https://pastebin.com/14aCyF2B](https://pastebin.com/14aCyF2B)

config:
[https://pastebin.com/dUemEQcN](https://pastebin.com/dUemEQcN)

plugin list:

- actionbar api
- announcer
- armorstand tools
- async world edit
- buycraftx
- chunk spawner limiter
- citizens
- core protect
- craftbook
- crazy auctions
- discordSRV
- dynmap
- dynmap-citizens
- dynmap-essentials
- dynmap-greifprevention
- editable signs
- essentialsx
- greifprevention
- Harbor
- head database
- holographic displays
- HorseTPWithMe
- marriage master
- mcmmo classic
- minepacks
- mineable spawners
- mob capture
- mobhunting
- multiverse core
- multiverse inventories
- multiverse netherportals
- multiverse portals
- multiverse signportals
- nerf phantoms
- openinv
- permissionsex
- placeholder api
- plot2dynmap
- plotsquared
- plugin lib
- plugman
- protocol lib
- server list plus
- tab
- tempfly
- time is money
- vault
- voting plugin
- wildernesstb
- world edit
- world guard

**Comment by stw222** [comment]
im still getting this error on 1.5.3

**Comment by nkomarn** [comment]
I am removing the need for events in the latest build of Harbor, so this should be resolved.
