### ISSUE TITLE
Re-Add delay

### ISSUE THREAD

**Issue by Joniator** [nkomarn/harbor#27]
The readme on spigotmc.org mentions a config named delay in the default config.

This setting doesnt seem to exist anymore.
My proposal would be to either re-add the feature or update the readme.

Personally we don't like the instant-skip, so a feature to add a delay would be great, the default value can still be no delay it this is the desired effect on your side.

**Comment by Joniator** [comment]
I dont have the needed jars locally so I couldn't build/test this, but I hope this doesn't break anything important

**Comment by nkomarn** [comment]
I am implementing smooth night skip, so this shouldn't be necessary anymore!
