### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by LadyHaley** [nkomarn/harbor#29]
Could you please add a world black list, I dont want to see any sleep msgs unless im in the overworld. Sleeping in the nether or end doesnt make much sense and theres no reason at all for it to be seen in the creative or minigame worlds

**Comment by nkomarn** [comment]
Added this feature in the latest build!

**Comment by nicegamer7** [comment]
I know this issue is closed, but can this be converted to a generic world list? And the list would have the option of blacklist or whitelist.

**Comment by nkomarn** [comment]
> I know this issue is closed, but can this be converted to a generic world list? And the list would have the option of blacklist or whitelist.

Sure thing, I'll get on that.

**Comment by nkomarn** [comment]
737c9bd implements this- I just made a toggle for `whitelist-mode` right below the list as an optional feature.
