### ISSUE TITLE
Ignore from afk system permission.

### ISSUE THREAD

**Issue by comonier** [nkomarn/harbor#30]
Please add an permission to staffs [vanish] 
Owners not having issues joining in stealth mode and ... 
have issues with messages in chat [ owner is afk ]  [  owner is back ]
Messages in chat.... i am owner i join in vanish but after the afk timer 
of config of Harbor plugin, it show on chat, to everyone i am not more afk.
so..... everyone start asking me something. ¬¬

**Comment by nkomarn** [comment]
Fixed in 1.6.
