### ISSUE TITLE
sleep loop

### ISSUE THREAD

**Issue by Decme** [nkomarn/harbor#31]
Had the plugin running 1.5.3 'fine' for a few irl days. Then this happened: https://i.ibb.co/qnYMSr3/2019-08-14-10-30-05.png

We could also do without the obnoxious messages. I run a mature server, and it looks like the plugin notifications are aimed at 12 year olds. Yes I know we can change the config, but it should be less obnoxious by default surely?

Ideally I'm looking for a % based sleep plugin that:
Notifies players "Player X is sleeping. Y out of Z players are sleeping to skip the night."
Upon morning, no notification message whatsoever. Keep it feeling vanilla.
Uses the ignore afk players system but does not mark players as afk. I don't want my playerbase to know who is or isn't afk. If someone afk's, it's their own private business. If my players decide to afk for 24 hours irl I have no issue with this.

**Comment by BytewaveMLP** [comment]
Pretty much every message can be customized/disabled through the config, just so you know.

**Comment by nkomarn** [comment]
@Decme Working on it!

**Comment by nkomarn** [comment]
This should no longer be an issue since the latest build!
