### ISSUE TITLE
Phantoms

### ISSUE THREAD

**Issue by ChipWolf** [nkomarn/harbor#32]
Instead of disabling Phantoms as they become irritating with Harbor for users not participating who don't get their 'time since rest' statistic reset. Can Harbor reset the statistic to prevent Phantoms spawning on those who didn't participate?

**Comment by ChipWolf** [comment]
```
import org.bukkit.Statistic;
...
for(Player player : w.getPlayers()) {
  player.setStatistic(Statistic.TIME_SINCE_REST, 0)
}
```
maybe?

**Comment by nkomarn** [comment]
@ChipWolf I'll implement this! Thank you for letting me know about this!

**Comment by Ricket** [comment]
Did this happen? We are on version 1.6.1 and getting phantoms attacking the person who is not sleeping

**Comment by nkomarn** [comment]
> Did this happen? We are on version 1.6.1 and getting phantoms attacking the person who is not sleeping

If the player isn't online when the night is skipped, their counter won't be reset as it stands currently.
