### ISSUE TITLE
Option for constant 'needed total'

### ISSUE THREAD

**Issue by FireController1847** [nkomarn/harbor#33]
What I mean is instead of the "needed" count counting down when a player sleeps, it would be nice if the needed count would be a constant divisor of the amount of players online. For example, if there's 4 players online and the count is 50%, I'd like the chat to go:

\<Player\> is now sleeping (1/2)
\<Player2\> is now sleeping (2/2)
Good morning!

But instead, with the current needed variable, it goes:

\<Player\> is now sleeping (1/1)
\<Player\> got out of bed (0/2)

Which is very confusing. It'd be very nice to have this as an option!

**Comment by nkomarn** [comment]
Added in 1.6 release candidate! Final 1.6 will be out soon, but if you would like to test out the rc, you can get it at https://harbor.nkomarn.xyz/!
