### ISSUE TITLE
Chat messages are not used?

### ISSUE THREAD

**Issue by mikroskeem** [nkomarn/harbor#39]
Chat messages are defined in plugin's configuration, yet they aren't used anywhere. Is this intentional? I favor chat messages over actionbar ones because actionbar messages aren't really noticeable.

**Comment by nkomarn** [comment]
@mikroskeem As of 1.6, I have removed bed enter/leave chat messages. Because many people requested the addition of these messages, I will re-implement them for the next version.

**Comment by nkomarn** [comment]
https://github.com/nkomarn/Harbor/commit/71dbe4e164ff6ab2a72d0252b8a994dcc60365cb re-implements the chat messages. I have a few other things to do before I release these changes, but expect messages to be back in 1.6.2.

**Comment by mikroskeem** [comment]
Great, thank you.
