### ISSUE TITLE
The "Everyone is Sleeping" msg doesn't clear

### ISSUE THREAD

**Issue by cjucoder** [nkomarn/harbor#4]
The message stays on screen forever until the sleeping count and skipped messages display.

**Comment by cjucoder** [comment]
![2018-12-06_12 35 25](https://user-images.githubusercontent.com/18238173/49694281-26fd7b00-fb4d-11e8-9940-2a2cc38d89f0.png)

**Comment by Synt3x** [comment]
Can you attach your config file? I may take a look at the problem.

**Comment by cjucoder** [comment]
Thanks. I made no changes to the default the config, but here it is anyway. Had to rename it to .txt to be able to attach it here.
[config.txt](https://github.com/nkomarn/Harbor/files/2668079/config.txt)

**Comment by Synt3x** [comment]
@cjucoder: If you okey playing without the actionbar, you can change `actionbar: true` to `actionbar: false` in the config.

How to reproduce the problem:
1. op account1
2. op account2
3. sign in on both accounts
4. the message now appears

**Comment by cjucoder** [comment]
@Synt3x: Thanks for taking the time to look through this. I'm sure the original plugin developer appreciates it too.

**Comment by nkomarn** [comment]
@cjucoder Can you test this with version 1.4.2 and tell me if the issue still occurs? I have fixed most the bugs with 1.13.2, but I haven't yet experienced this one so I am not sure if it's fixed.

**Comment by cjucoder** [comment]
Will do. Thank you.
