### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by lae** [nkomarn/harbor#40]
Thanks for this plugin! Any chance you could also publish releases on Github when they're out? It'd let folks like me watch this repository for releases to get notified (since I don't have an account on the Spigot website, and I assume you can watch for updates there).

**Comment by nkomarn** [comment]
> Thanks for this plugin! Any chance you could also publish releases on Github when they're out? It'd let folks like me watch this repository for releases to get notified (since I don't have an account on the Spigot website, and I assume you can watch for updates there).

I'll make sure to publish new releases on GitHub as well!
