### ISSUE TITLE
Latest beta - day / night loops endlessly until config is deleted

### ISSUE THREAD

**Issue by Kwikxilver** [nkomarn/harbor#46]
Loaded the latest beta version with the new day_cycle function, but didn't delete my config. Day and night were looping endlessly. I deleted my config and had it generate a new one, worked fine after that.

You might want to put a note that people will have to delete their configs when loading this new version.

**Comment by nkomarn** [comment]
@yntel I had the exact same issue on my server- currently looking into a way to fix it without forcing config resets because I'm sure a lot will skip over that suggestion and leave negative feedback.

**Comment by Kwikxilver** [comment]
@nkomarn Great stuff. Thanks for your work on this plugin mate.

**Comment by nkomarn** [comment]
04994ed should fix this issue since the config is going to need to be regenerated either way after the update.
