### ISSUE TITLE
[Feature Request] Make time move proportionally to percentage of players sleeping

### ISSUE THREAD

**Issue by resindrake** [nkomarn/harbor#47]
It'd be a really useful feature if the night went faster the more players were sleeping, up to instant-vanilla speed if 100% of players are asleep.

**Comment by nkomarn** [comment]
Would you want time to start increasing when a threshold of sleeping players is reached or just start when a single person is in bed?

**Comment by resindrake** [comment]
I'd say tie it to the pre-existing threshold in the config, with an extra flag to enable this proportional acceleration.

Let me give an example to be more clear what I mean:
Say you have 8 people on a server, and the threshold is 4:
0-3 people wouldn't accelerate time at all.
4-8 people would accelerate time by 20%, 40%, 60%, 80%, and finally 100% for all 8 people.

Edit: (100% being the full default acceleration speed that the mod already uses)

**Comment by nkomarn** [comment]
Implemented in f727f27- please reopen the issue if you have any other requests related to this feature or find issues with the implementation. Thanks for the suggestion :)
