### ISSUE TITLE
v1.4.2 null pointer exceptions when OP sleeps

### ISSUE THREAD

**Issue by cjucoder** [nkomarn/harbor#5]
An op attempting to sleep causes the following errors ....

Could not pass event PlayerBedEnterEvent to Harbor v1.4.2
org.bukkit.event.EventException: null
---snip stack trace---
Could not pass event PlayerBedLeaveEvent to Harbor v1.4.2
org.bukkit.event.EventException: null
----snip---

I was the only player and the night did pass.  When I deop'ed myself there were no errors.
Attached is the full log.
[latest.log](https://github.com/nkomarn/Harbor/files/2688894/latest.log)

edited to add...
Even as OP when I set harbor.bypass to false the null pointer exceptions did NOT occur.

**Comment by nkomarn** [comment]
Ugh, I knew there was an error somewhere haha. I'll fix this up- I thought I totally fixed that part but eh I guess not. Anyways, thanks for notifying me :)

**Comment by nkomarn** [comment]
@cjucoder I've fixed it (hopefully) in the latest update. If you can, give it a quick test and let me know if anything else is broken. I'll make sure to fix any issues promptly!
