### ISSUE TITLE
Harbor 1.6.1 messages not sent in chat

### ISSUE THREAD

**Issue by ghost** [nkomarn/harbor#50]
Hi ! 

Thanks again for the great plugin.
On my server i'd like to send the messages of people sleeping into the chat.

Action bar works but i disabled it. Unfortunatly no messages in the chat.

Any ideas why ? 

I am recieving all chat messages concerning night.

Best regards,
Thank you for your help

**Comment by nkomarn** [comment]
Harbor 1.6.1 doesn't have chat messages. However, I re-implemented them in the Harbor 1.6.2 beta builds, which you can download [here](https://github.com/nkomarn/Harbor/releases/tag/1.6.2-b6). Keep in mind that you will have to delete your old config for the beta to work correctly.
