### ISSUE TITLE
[Feature] Don't show bed leave messages after night has been skipped

### ISSUE THREAD

**Issue by AfkF24** [nkomarn/harbor#51]
What the title suggests. Bed leave messages would still pop up in chat, even after the night has been skipped. Doesn't happen always, but rather occasionally.

**Comment by nkomarn** [comment]
I'll do some testing with this on my server and see if I get the same behavior.

**Comment by AfkF24** [comment]
As a side note, `clear-rain` and `clear-thunder` don't seem to be working as well.

**Comment by nkomarn** [comment]
I haven't experienced either of these issues in the latest beta release.

**Comment by AfkF24** [comment]
> I haven't experienced either of these issues in the latest beta release.

Oh, I should update to beta 6 and report back then. I was running b5.

**Comment by AfkF24** [comment]
Just to update you on this, I don't seem to be having these issues on b6. Will be closing the issue, thanks! :)
