### ISSUE TITLE
Add afk player support that doesn't require Essentials

### ISSUE THREAD

**Issue by Decme** [nkomarn/harbor#52]
Please could you add the option to ignore afk players without requiring EssentialsX? I've mostly had bad experience with Essentials & would prefer not to use that plugin.

**Comment by nkomarn** [comment]
The latest beta releases re-add Harbor's built-in AFK detection system. You can download them here: https://github.com/nkomarn/Harbor/releases/tag/1.6.2-b6. Keep in mind that you will have to regenerate your configuration when updating :")
