### ISSUE TITLE
"harbor forceskip" command doesn't work.

### ISSUE THREAD

**Issue by TotallyNotSethP** [nkomarn/harbor#55]
On my Windows 10 system, the command "/harbor forceskip" returns "[Server thread/INFO]: (Harbor) Unrecognized command."

**Comment by nkomarn** [comment]
> On my Windows 10 system, the command "/harbor forceskip" returns "[Server thread/INFO]: (Harbor) Unrecognized command."

What Harbor build are you using?

**Comment by TotallyNotSethP** [comment]
"Harbor version 1.6.1 by TechToolbox (@nkomarn)."

**Comment by nkomarn** [comment]
`/harbor forceskip` was only added in the 1.6.2 betas, which is why you can't use it on 1.6.1. Check the releases page of this repository if you want to use the betas- you will need to regenerate your configuration since the betas have a new format.
