### ISSUE TITLE
Another server that uses harbor

### ISSUE THREAD

**Issue by FireController1847** [nkomarn/harbor#57]
Hey there, I've been a pretty avid Harbor user and I noticed on your Spigot page you have a "servers that use harbor" category.

I host a server called Friends Vanilla, whose goal is to stay online for a lifetime. Would you want to add it?

https://www.friendsvanilla.net/

The server IP is friendsvanilla.net

If not I totally understand, was just wondering if you wanted another server to add to your list ;)

**Comment by ExZiByte** [comment]
Is the server a publicly joinable server

**Comment by FireController1847** [comment]
Yes it is, and while it is in beta right now everyone can join and we are accepting new players. Similarly, I am almost completed with being in beta and it will be releasing fully (aka I will begin advertising) in about a month or two.

It is fully joinable and playable by anyone right now, however.

**Comment by nkomarn** [comment]
I've added your server to the Harbor page. Sorry about the wait!

**Comment by FireController1847** [comment]
No problem! Thanks for considering :)
