### ISSUE TITLE
Multiple bossbar

### ISSUE THREAD

**Issue by matahombres** [nkomarn/harbor#58]
![image](https://user-images.githubusercontent.com/17030845/86614189-e9740480-bfb2-11ea-89a2-8cc8441e99f5.png)

Server: paperspigot 1.15.2 - build 318
Version: 1.6.2 beta 6

**Comment by nkomarn** [comment]
I'll look into the cause of this.

**Comment by nkomarn** [comment]
This bug should be fixed as of Harbor 1.6.2 beta 7. Give it a try and re-open this issue if you continue to experience the problem: https://github.com/nkomarn/Harbor/releases.
