### ISSUE TITLE
Issue with showing sleeping players

### ISSUE THREAD

**Issue by wildmanviper** [nkomarn/harbor#59]
Ive downloaded and installed the latest version of your plugin from https://www.spigotmc.org/resources/harbor-a-sleep-enhancement-plugin.60088/ and have noticed that we get the "[sleeping] out of [needed] players are sleeping ([more] more needed to skip)." # Shown when some players are in bed" but not who is sleeping ""&e[player] is now sleeping ([sleeping]/[needed], [more] more needed to skip)." # Display which player went to bed"  Just cant figure out what I need to do to display this information.

**Comment by ExZiByte** [comment]
What version of the game is your server running

**Comment by wildmanviper** [comment]
1.16.1 right now.   I actually just found a old thread that said it wasnt
working and was going through testing in 1.16.2 beta from here:
https://github.com/nkomarn/Harbor/releases/tag/1.6.2-b6

**Comment by ExZiByte** [comment]
Yep was just about to say to update to the latest version the repo

**Comment by wildmanviper** [comment]
I appreciate your fast response.  Thank you very much.
