### ISSUE TITLE
Night is instantly skipped & weather is cleared if sleeping as a single person on server, even if harbor.bypass is enabled

### ISSUE THREAD

**Issue by Jujumatic** [nkomarn/harbor#60]
Steps to reproduce:

1. Enable harbor.bypass on your player
2. Enable an interval in the config e.g. interval: 10 for how long the transition to skip night takes
3. Put weather: false in the config to stop weather being modified when skipping night
4. Join the server and play as the only person online
5. Enter a bed during night-time and in rain

Night is instantly skipped and weather is cleared. Same thing happens if you do not have harbor.bypass

Running paperMC 1.16.1 version 110

Possible causes: Vanilla behaviour is being enforced even with this plugin enabled?

**Comment by kotyk7** [comment]
If you have Essentials installed try to negate `essentials.sleepingignored` permission.

**Comment by nkomarn** [comment]
Please make sure to use the latest build of Harbor and check to make sure the permission `essentials.sleepingignored` is negated if you are running EssentialsX on your server. Feel free to reopen this issue if the problem persists.
