### ISSUE TITLE
EssentialsX Instant Skip Issue

### ISSUE THREAD

**Issue by FireController1847** [nkomarn/harbor#62]
Server Version: Paper 1.16.1 Build 117
Plugin Version: 1.6.2 Beta 6
Essentials Version: 2.18.0.7

When I am the only player on the server, and/or when everyone on the server is sleeping, it instantly skips the night regardless of the `instant-skip` setting in the config. This only happens with EssentialsX installed.

**Comment by nkomarn** [comment]
You need to negate the permission `essentials.sleepingignored` from all players in your permissions manager. This is an unfortunate feature of Essentials that often conflicts with Harbor.

**Comment by FireController1847** [comment]
Hey there, thanks for the quick response. Unfortunately, that does not appear to have fixed the issue. I have de-opped myself and removed all essentials permissions, and then have set `essentials.sleepingignored` to `false` using LuckPerms on myself. However, upon sleeping the night still skips instantly.
