### ISSUE TITLE
Harbor commands

### ISSUE THREAD

**Issue by aidenmitchell** [nkomarn/harbor#65]
I used to use Harbor on a server a while ago and I recall there being a command to manually skip to day that operators could use. Is that still a thing? Thanks!

**Comment by ExZiByte** [comment]
Yes that command is still available it is 

> /harbor forceskip

**Comment by aidenmitchell** [comment]
It's saying it's an unrecognized command.

**Comment by nkomarn** [comment]
As far as I remember, that command is only available in the latest beta releases of Harbor. You can grab those from the releases page on this repo. You will have to reset your configuration file if you choose to update.
