### ISSUE TITLE
Harbor 1.6.2 sends "Outdated Configuration" Message to Wrong People

### ISSUE THREAD

**Issue by scberends** [nkomarn/harbor#67]
Harbor version 1.6.2 appears to send the "Outdated Configuration" message to all players besides /OP's.

Paper version: 1.6.3 v206.

**Comment by ExZiByte** [comment]
This has been found already and I'm not sure if nkomarn has put out a fix for it yet

**Comment by nkomarn** [comment]
Fixed as of b2b3baccf4a9bd8a4401684b248131cdf8b6e97f.
