### ISSUE TITLE
Regenerate Configuration

### ISSUE THREAD

**Issue by BeachnDude** [nkomarn/harbor#68]
Thanks for this plugin... I went to update it, and now when I log on to the server it states: "Your Harbor configuration is outdated- please regenerate it or Harbor may not work properly". How would I go about regenerating the config? Thanks In Advance

**Comment by nkomarn** [comment]
You would have to simply delete the old configuration file in your plugins folder and restart the server. Any old changes would have to be manually moved over.

**Comment by BeachnDude** [comment]
You should have ended with "& Ta Da !!"  Thanks Again...
