### ISSUE TITLE
Support for player nicknames

### ISSUE THREAD

**Issue by Rivest8** [nkomarn/harbor#69]
Can you add support for nicknames in messages. [player_nick] It's confusing for players that are known by their nickname to see "realname is now sleeping".

**Comment by nkomarn** [comment]
Try using the [displayname] placeholder.

**Comment by Rivest8** [comment]
Thanks. I didn't know that was a command. It works for now but that includes the prefix in the name. I was hoping for something that only showed the nickname.
"[Admin] nickname is now sleeping" versus "nickname is now sleeping"
