### ISSUE TITLE
Console Spammed with error

### ISSUE THREAD

**Issue by nunavailabul** [nkomarn/harbor#8]
Plugin appears to be working (haven't tested with people in different worlds yet though) it is just constantly spitting out errors in the console.

**Server Info**
CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Plugins (28): WorldEdit, Harbor, WorldGuard, ProtocolLib, Core, AdvancedPortals, tpa, VoidGenerator, PermissionsEx, ArvinLib, mcMMO, Vault, GWarp, DeathTax, Herochat, TheNewEconomy, Jobs, PerWorldInventory, HolographicDisplays, PlotSquared, Multiverse-Core, HoloPlots, CrazyAuctions, Multiverse-NetherPortals, GriefPrevention, MV-ChatAlias, CommandSigns, RandomTeleport

*edit: Using latest jar for Harbor

**Error**
`[10:39:36 WARN]: [Harbor] Task #21 for Harbor v1.4.3 generated an exception
java.lang.NullPointerException: null
        at techtoolbox.Harbor.ActionBarMessage.run(ActionBarMessage.java:9) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-140f654-b446cb5]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by nkomarn** [comment]
@nunavailabul Thanks for letting me know about this! I'll experiment and see what I can do to fix this!

**Comment by nkomarn** [comment]
> 
> 
> Plugin appears to be working (haven't tested with people in different worlds yet though) it is just constantly spitting out errors in the console.
> 
> **Server Info**
> CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
> 
> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
> 
> Plugins (28): WorldEdit, Harbor, WorldGuard, ProtocolLib, Core, AdvancedPortals, tpa, VoidGenerator, PermissionsEx, ArvinLib, mcMMO, Vault, GWarp, DeathTax, Herochat, TheNewEconomy, Jobs, PerWorldInventory, HolographicDisplays, PlotSquared, Multiverse-Core, HoloPlots, CrazyAuctions, Multiverse-NetherPortals, GriefPrevention, MV-ChatAlias, CommandSigns, RandomTeleport
> 
> *edit: Using latest jar for Harbor
> 
> **Error**
> `[10:39:36 WARN]: [Harbor] Task #21 for Harbor v1.4.3 generated an exception java.lang.NullPointerException: null at techtoolbox.Harbor.ActionBarMessage.run(ActionBarMessage.java:9) ~[?:?] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-140f654-b446cb5] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-140f654-b446cb5] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

Try Harbor version 1.4.4 and let me know if the same issue occurs! I haven't had spam reports with that update yet, but let me know what your experience is!
