### ISSUE TITLE
OP Always Excluded

### ISSUE THREAD

**Issue by CatzPJzJakey** [nkomarn/harbor#9]
I have changed the config's "bypass" option for OP's back and forth now, restarting and reloading the server, and it still won't allow me to be counted.

**Comment by nkomarn** [comment]
@CatzPJzJakey I'm working on fixing this issue for the next release :)

**Comment by CatzPJzJakey** [comment]
Okay, cool! Thank you, at least it's not crashing like the previous bug, lol. Thank you for fixing that as well. :)

**Comment by nkomarn** [comment]
> 
> 
> Okay, cool! Thank you, at least it's not crashing like the previous bug, lol. Thank you for fixing that as well. :)

Hopefully fixed it! https://www.spigotmc.org/resources/harbor-a-sleep-enhancement-plugin.60088/download?version=257881
