### ISSUE TITLE
Thunderstorms Creating Infinite Night

### ISSUE THREAD

**Issue by TalrothNai** [nkomarn/harbor#92]
Players were trying to sleep to skip the night and a Thunderstorm which was happening at the same time and it was creating an infinite night. It would cycle through the messages saying accelerating the night, rapidly approaching daytime, ahh, finally morning, everyone is sleeping - sweet dreams, etc...

night-skip:
enabled: true
clear-rain: true
clear-thunder: true
instant-skip: true

If there's other properties you need from the config.yml let me know.

**Comment by mawoka-myblock** [comment]
Same problem!

**Comment by nkomarn** [comment]
> Same problem!

Try the latest beta release of Harbor (https://github.com/nkomarn/harbor/releases/tag/1.6.4-b1) and see if your problem is solved.

**Comment by mawoka-myblock** [comment]
> > Same problem!
> 
> Try the latest beta release of Harbor (https://github.com/nkomarn/harbor/releases/tag/1.6.4-b1) and see if your problem is solved.

Sorry, don't want to try beta-build in production, but thanks for your super-fast response, or is the beta-build "stable"?

**Comment by nkomarn** [comment]
Should be stable; I've been using it on my own server for a while now without issue.
